```{r message=FALSE, warning=FALSE}
library("tidyverse")
library("janitor")
library(paletteer)
library(dplyr)
```

```{r}
my_palette <- paletteer_d("dutchmasters::little_street") 
```

```{r}
install.packages("paletteer")
```

```{r}
bigfoot1<- read.csv("data/bigfoot_updated_CAonly_noNA.csv", na = c("NA", " ", ".", "-999"))
```

```{r}
bigfoot1 %>%
  filter(season!="Unknown") %>%
  ggplot(aes(x=season, fill = season))+
  geom_bar()+
  scale_fill_manual(values=my_palette)+
  theme(plot.title = element_text(size=rel(3), hjust=.5), axis.title.x = element_text(size = 25, color = "black"), axis.title.y = element_text(size = 25, color = "black"), legend.text=element_text(size=rel(2)),legend.key.size = unit(1, "cm"))+
  labs(title = "California Bigfoot Sightings by Season", x="Season", y="Count")+
  ggsave(file="seasons.png", width = 12, height = 10, dpi=300)
  
```

```{r}
bigfoot1 %>%
  ggplot(aes(temperature_mid))+
  geom_histogram(na.rm=T, bins = 25, color="white")+
  scale_fill_manual(values=my_palette)+
  labs(title = "Average Temperature Range During Recorded Sightings", x="Temperature (C)", y="Count")+
  facet_wrap(~season)+
  ggsave(file="temp.png", width = 15, height = 8, dpi=300)
```

```{r}
bigfoot1 %>%
  filter(conditions!=" ") %>%
  ggplot(aes(x=conditions, fill = conditions))+
  geom_bar(color="black")+
  scale_fill_manual(values=my_palette)+
  labs(title = "Sightings by Weather", x="Weather", y="Count")+
  theme(legend.position="top")+
  coord_flip()+
  theme(plot.title = element_text(size=rel(3), hjust=.5), axis.title.x = element_text(size = 25, color = "black"), axis.title.y = element_text(size = 25, color = "black"), legend.text=element_text(size=rel(1)),legend.key.size = unit(0.6, "cm"))+

  ggsave(file="conditions.png", width = 10, height = 9, dpi=300)
```

```{r}
cali_locs <- bigfoot1 %>%
  mutate(locations = case_when(latitude<=36.499998 ~"Southern",
                                   latitude>36.499998 ~"Northern"))
```
```{r}
 cali_locs %>%
  group_by(county) %>%
  summarize(n=n())%>%
  filter(n>=5)
```


```{r}
cali_county <- cali_locs %>%
  group_by(county) %>%
  mutate(n=n())%>%
  filter(n>=5)

cali_county
```


```{r}
cali_county %>%
  ggplot(aes(x=county, fill=locations))+
  geom_bar()+
  coord_flip()+
  scale_fill_manual(values=my_palette)+
  labs(title = "Bigfoot Sightings by County", x="County", y="Count")+
  theme(plot.title = element_text(size=rel(3), hjust=.5), axis.title.x = element_text(size = 25, color = "black"), axis.title.y = element_text(size = 25, color = "black"), legend.text=element_text(size=rel(2)),legend.key.size = unit(1, "cm"))+
ggsave(file="bigfootcounty.png", width = 12, height = 10, dpi=300)
```

```{r}
cali_locs %>%
  ggplot(aes(x=classification, fill=classification))+
   scale_fill_manual(values=my_palette)+
  geom_bar()+
  labs(title = "Bigfoot Sightings By Classification", x="Classification", y="Sightings Count")+
  theme(plot.title = element_text(size=rel(3), hjust=.5), axis.title.x = element_text(size = 25, color = "black"), axis.title.y = element_text(size = 25, color = "black"), legend.text=element_text(size=rel(2)),legend.key.size = unit(1, "cm"))+
  ggsave(file="classificationwithcolor.png", width = 10, height = 10, dpi=300)

  
```
`


```{r}
n_distinct(bigfoot1$county)
```

```{r}
bigfootmaps <- read.csv("data/bigfoot_updated_CAonly_noNA.csv")

bigfootDated_Jenn <- bigfootmaps %>%
  separate(date, into= c("month", "day", "year"), sep = "/")

#check for non-numeric entries
as.numeric(bigfootDated_Jenn$month)

#correct entry in weird date format
bigfootDated_Jenn$month[5]
bigfootDated_Jenn$month[5]<-11
bigfootDated_Jenn$day[5]<- 10
bigfootDated_Jenn$year[5]<- 1869
bigfootDated_Jenn[5,]
```

```{r}
bigfootDated_Jenn %>%
  factor(month, levels = 12) %>%
  ggplot(aes(x=month, fill=classification))+
  geom_histogram(stat='count')+
  scale_fill_manual(values=my_palette)+
  labs(title = "Bigfoot Sightings By Month", x="Month", y="Sightings Count")+
  theme(plot.title = element_text(size=rel(3), hjust=.5), axis.title.x = element_text(size = 25, color = "black"), axis.title.y = element_text(size = 25, color = "black"), legend.text=element_text(size=rel(2)),legend.key.size = unit(1, "cm"))+
  ggsave(file="months.png", width = 10, height = 10, dpi=300)
```
```{r}
bigfootDated_Jenn %>%
  ggplot(aes(x=month))+
  geom_bar()
```


```{r}
bigfootDated_Jenn %>%
  group_by(month) %>%
  summarize(total=n())
```
