---
title: "So not winning"
output: html_document
---

```{r}
library(shiny)
library(leaflet)
library(sf)
library("shinythemes")
library(dplyr)
library("tidyr")
library(shinydashboard)
library("janitor")
library("stringr")
library('dbplyr')
library('readr')
library('data.table')

bigfootmaps <- read.csv("data/bigfoot_updated_CAonly_noNA.csv")

temp_shapefile <- tempfile()
download.file("https://www2.census.gov/geo/tiger/TIGER2019/COUSUB/tl_2019_06_cousub.zip", temp_shapefile)
unzip(temp_shapefile)

sf_county <- read_sf('tl_2019_06_cousub.shp')
```
```{r}
bigfootmaps <- read.csv("data/bigfoot_updated_CAonly_noNA.csv")

bigfootDated_Jenn <- bigfootmaps %>%
  separate(date, into= c("month", "day", "year"), sep = "/")


   #check for non-numeric entries
as.numeric(bigfootDated_Jenn$month)

#correct entry in weird date format
bigfootDated_Jenn$month[5]
bigfootDated_Jenn$month[5]<-11
bigfootDated_Jenn$day[5]<- 10
bigfootDated_Jenn$year[5]<- 1869
bigfootDated_Jenn[5,]


bigfootDated2<- bigfootDated_Jenn %>%
   mutate(month = month.abb[as.numeric(month)])
```


```{r}
library(shinydashboard)
library(shinythemes)
ui <- dashboardPage(
   dashboardHeader(title = "SASQWATCH"),
  
  ## Sidebar content
  dashboardSidebar(
    sidebarMenu(
      
      menuItem("Map", 
               tabName = "map"),
      
      menuItem("Plan a sighting", 
               tabName = "plan_a_sighting")
    )
    ),
  
  ## Body content
  dashboardBody(
    
    tabItems(
  
      ## First tab content    
      tabItem(tabName = "map",
      fluidPage(
  theme = shinytheme("flatly"),
  
  titlePanel("My Bigfoot Sightings Map"),
box(
      selectInput("x", 
                  "Select Classification", 
                  choices = unique(bigfootmaps$classification), 
                  selected = "Class A"),
      selectInput("y", 
                  "Select Weather", 
                  choices = unique(bigfootmaps$conditions), 
                  selected = "Clear")
  
)
),

leafletOutput(outputId = "map1") #make sure this matches with the renderLeaflet in server output
  ),

 ## Second tab item 
      tabItem(tabName = "plan_a_sighting",
        fluidPage(
box(title = "Plot Options", 
          width = 3, #adjust the column width
              
                selectInput("a", 
                            "Select County",
                            choices = sort(unique(bigfootDated_Jenn$county)), #instead of typing all options, we can use unique()
                            selected="Amador County"),
                selectInput("b", 
                            "Select Month", 
                            choices = c("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"),
                            selected="Jan"),
                          
                selectInput("c", 
                            "Select day", 
                            choices = c(1:31), 
                            selected="1"),
           
    
    ),
box(title = "Check your chance of seeing bigfoot", width = 8, #adjust the column width and add title
     plotOutput( "plot", width="350px", height="400px"), 
    ), # close the second box  

), # close the first box    



br(),
 box(title = "history", width = 3, height = "150px",
         column(3,
          tableOutput('table') 


      ) 


) # close the row         

          )
          )
  )
)

          


server <- function(input, output, session) {

  output$map1 <- renderLeaflet({
    
    filtered_data <- bigfootmaps %>% 
      dplyr::filter(classification == input$x) %>%
      dplyr::filter(conditions == input$y)
      
    
    filtered_data %>% 
      leaflet(sf_county) %>% 
      addTiles() %>%  # Optionally keep or remove this line if not needed
      addCircleMarkers(
        lng = ~longitude, 
        lat = ~latitude, 
        popup = ~as.character(bigfootmaps$date), 
        label = ~as.character(bigfootmaps$date),
        radius = 5,           
        color = "blue",       
        fillColor = "cyan",   
        fillOpacity = 0.7     
      ) %>%
      setView(lng = -121.771598, 
              lat = 38.533867, 
              zoom = 5.5) %>%
      addPolygons(data=sf_county, color = "black", weight = 1, fillColor="thistle", opacity=0.7 )%>%
      addProviderTiles('Stamen.Terrain')
     
  })
  
    output$plot <- renderPlot({
    session$onSessionEnded(stopApp) # stop the app when we close it
  
  output$plot <- renderPlot({
  user_vector <- reactiveValues()

  
value<-c(a,5,7)

value$a <- bigfootDated_Jenn %>%
  count(county)%>%  
  arrange(-n)%>% 
  mutate(total=sum(n))%>%
  filter( county == input$a)%>%
  mutate(perc_CA_sightings = (n/total)*100)    

value$b <-  bigfootDated2 %>%
  count(month)%>%
  arrange(-n)%>% 
  mutate(total=sum(n))%>%
  filter(month == input$b)%>%
  mutate(perc_sightings_month = (n/total)*100)

value$c <- bigfootDated_Jenn %>%
  count(day)%>%
  arrange(-n)%>% 
  mutate(total=sum(n))%>%
  filter(day== input$c)%>%
  mutate(perc_sightings_day = (n/total)*100)




param<- c(input$a,input$b,input$c)
value<- c(value$a[4],value$b[4],value$c[4])



print("PARAM")
print(param)
print("VALUE")
print(value)

param<-as.factor(param)
value<-as.double(value)


trial<- data.frame(param, value) 
class(param)
class(value)
print(trial)

      v<- c(trial$value[1]/trial$value[2]*trial$value[3])
   
 
trial %>%
      ggplot(aes(x=param, y=value)) + 
      geom_col() +
         labs(x = "parameter", y = "percent of total sightings in california by parameter")+
     ggtitle(paste("Calculated chance of seeing bigfoot ", v, "%"))    



output$table <- renderTable(bigfootDated2, select(bigfootDated2$classification), filter(bigfootDated2classification == "Class A")) 





    
  })
})
   
    
#  })
    
}

shinyApp(ui, server)
```

