---
title: "So not winning"
output: html_document
---

```{r}
library(shiny)
library(leaflet)
library(sf)
library("shinythemes")
library(dplyr)
library("tidyr")
library(palmerpenguins)

bigfoot <- read.csv("data/bigfoot_updated_CAonly_noNA.csv")

temp_shapefile <- tempfile()
download.file("https://www2.census.gov/geo/tiger/TIGER2019/COUSUB/tl_2019_06_cousub.zip", temp_shapefile)
unzip(temp_shapefile)

sf_county <- read_sf('tl_2019_06_cousub.shp')
```

```{r}
library(shinydashboard)
ui <- dashboardPage(
   dashboardHeader(title = "Bigfoot App!"),
  
  ## Sidebar content
  dashboardSidebar(
    sidebarMenu(
      
      menuItem("Map", 
               tabName = "map"),
      
      menuItem("SasquWatch", 
               tabName = "watch")
    )
    ),
  
  ## Body content
  dashboardBody(
    
    tabItems(
  
      ## First tab content    
      tabItem(tabName = "map",
      fluidPage(
  theme = shinytheme("flatly"),
  
  titlePanel("My Bigfoot Sightings Map"),
box(
      selectInput("x", 
                  "Select Classification", 
                  choices = unique(bigfoot$classification), 
                  selected = "Class A"),
      selectInput("y", 
                  "Select Weather", 
                  choices = unique(bigfoot$conditions), 
                  selected = "Clear")
  
)
),

leafletOutput(outputId = "map1") #make sure this matches with the renderLeaflet in server output
  ),
 ## Second tab item 
      tabItem(tabName = "watch",
        fluidPage(
  selectInput("a", 
                "Select X Variable", 
                choices = c("bill_length_mm", "bill_depth_mm", "flipper_length_mm", "body_mass_g"), 
                selected = "bill_length_mm"),
    
    selectInput("b", 
                "Select Y Variable", 
                choices = c("bill_length_mm", "bill_depth_mm", "flipper_length_mm", "body_mass_g"), 
                selected = "body_mass_g"),
    plotOutput("plot2", width="500px", height="400px")         

          )
          )
  )
          )
          )


server <- function(input, output, session) {

  output$map1 <- renderLeaflet({
    
    filtered_data <- bigfoot %>% 
      dplyr::filter(classification == input$x) %>%
      dplyr::filter(conditions == input$y)
      
    
    filtered_data %>% 
      leaflet(sf_county) %>% 
      addTiles() %>%  # Optionally keep or remove this line if not needed
      addCircleMarkers(
        lng = ~longitude, 
        lat = ~latitude, 
        popup = ~as.character(bigfoot$date), 
        label = ~as.character(bigfoot$date),
        radius = 5,           
        color = "blue",       
        fillColor = "cyan",   
        fillOpacity = 0.7     
      ) %>%
      setView(lng = -121.771598, 
              lat = 38.533867, 
              zoom = 5.5) %>%
      addPolygons(data=sf_county, color = "black", weight = 1, fillColor="thistle", opacity=0.7 )%>%
      addProviderTiles('Stamen.Terrain')
     
  })
  
    output$plot2 <- renderPlot({
    ggplot(data=penguins,
           aes_string(x=input$a, y=input$b, color="species"))+ #make sure to use aes string when the input is involved there
      geom_point(na.rm=T)+
      theme_light (base_size=14)
   
    
  })
    
}

shinyApp(ui, server)
```

